### ISSUE TITLE
No sensor found

### ISSUE THREAD

**Issue by PatricDahl** [kayjei/homeassistant#1]
Hi,

Have installed component and below code in configuration.yaml but there no trace of sensor, checked logs and found nothing.
Have anything been changed on API side since your last update? Or i'm doing something wrong? 

  - platform: temperatur_nu
    name:
      - sodra_savedalen

BR
Patric Dahl

**Comment by kayjei** [comment]
Hi @PatricDahl,

Your code seems fine. When testing it appears that no sensor is created when selecting only 1.
You can try to input several of them, that should do it.
I will look into the issue

K-J

**Comment by PatricDahl** [comment]
Hi,

Added two more now three in total no on show up.
I Turned on debugging and got this error. Could invalid token (last line)
be the reason?

2022-01-20 17:49:11 DEBUG (SyncWorker_4)
[custom_components.temperatur_nu.sensor] Entity from list: sodra_savedalen
2022-01-20 17:49:11 DEBUG (SyncWorker_4)
[custom_components.temperatur_nu.sensor] Entity from list: partille
2022-01-20 17:49:11 DEBUG (SyncWorker_4)
[custom_components.temperatur_nu.sensor] Entity from list: delsjon
2022-01-20 17:49:11 DEBUG (SyncWorker_4)
[custom_components.temperatur_nu.sensor] Created URL:
http://api.temperatur.nu/tnu_1.17.php?verbose&cli=homeassistant_f616a23c&p=sodra_savedalen,partille,delsjon
2022-01-20 17:49:13 ERROR (MainThread) [homeassistant.components.sensor]
Error while setting up temperatur_nu platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in
run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/temperatur_nu/sensor.py", line 50, in
setup_platform
ApiRequest.call(URL)
File "/config/custom_components/temperatur_nu/sensor.py", line 177, in call
xmlObj = xmltodict.parse(response.content)
File "/usr/local/lib/python3.9/site-packages/xmltodict.py", line 327, in
parse
parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1,
column 0

BR
Patric

Den tors 20 jan. 2022 kl 15:36 skrev kayjei ***@***.***>:

**Comment by PatricDahl** [comment]
Hi Again,

Please ignore my previous post. My self- modified API version in request
and debug output is misleading.

Changed back to your original code and now it´s working.

2022-01-20 17:56:05 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Entity from list: sodra_savedalen
2022-01-20 17:56:05 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Entity from list: partille
2022-01-20 17:56:05 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Entity from list: delsjon
2022-01-20 17:56:05 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Created URL:
http://api.temperatur.nu/tnu_1.15.php?verbose&cli=homeassistant_89ba6f0c&p=sodra_savedalen,partille,delsjon
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Sending API request to:
http://api.temperatur.nu/tnu_1.15.php?verbose&cli=homeassistant_89ba6f0c&p=sodra_savedalen,partille,delsjon
Printing result to .temperatur_nu.json
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Reading .temperatur_nu.json for
device
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Creating poller device: delsjon
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] New sensor: Delsjön
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Sending API request to:
http://api.temperatur.nu/tnu_1.15.php?verbose&cli=homeassistant_89ba6f0c&p=sodra_savedalen,partille,delsjon
Printing result to .temperatur_nu.json
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Reading .temperatur_nu.json for
device
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Temp is 0.2 for Delsjön
2022-01-20 17:56:06 INFO (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Adding sensor: delsjon
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] New sensor: Göteborg/Partille
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Reading .temperatur_nu.json for
device
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Temp is -1.5 for Göteborg/Partille
2022-01-20 17:56:06 INFO (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Adding sensor: partille
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] New sensor: Göteborg/Södra
Sävedalen
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Reading .temperatur_nu.json for
device
2022-01-20 17:56:06 DEBUG (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Temp is 0.1 for Göteborg/Södra
Sävedalen
2022-01-20 17:56:06 INFO (SyncWorker_1)
[custom_components.temperatur_nu.sensor] Adding sensor: sodra_savedalen

Den tors 20 jan. 2022 kl 15:36 skrev kayjei ***@***.***>:

**Comment by kayjei** [comment]
Great news!
Also, there is a new version available containing the patch. Please update if you prefer a single sensor

K-J
